name: Continuous Delivery

on: workflow_dispatch

jobs:
  delivery:
    runs-on: ubuntu-latest
    name: Build & Deploy

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v3

      - name: Install dependencies
        run: pdm install --no-lock

      - name: Build application
        run: make build

      - name: Configure credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Deploy application
        run: aws s3 sync ./app/build s3://${{ secrets.AWS_S3_BUCKET_NAME }} --delete
